name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  GPT-CODE-REVIEW:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: gpt-4o
          PROMPT: "Provide a **concise** and **actionable** code review. Focus only on **major issues, improvements, and best practices**. 
                             When suggesting improvements, **include direct code snippets** (only if necessary). 
                             Keep responses **brief** and **to the point** (no more than 3-5 sentences per issue). 
                             Use bullet points for clarity."

